repos:
  - repo: local
    hooks:
      - id: hatch-lint
        name: Running lint checks before pushing, please wait...
        entry: hatch run lint
        language: system
        types: [python]
        stages: [pre-push]