name: Deploy
run-name: Deploy

on:
  workflow_call:
    inputs:
      target_tag:
        type: string
        description: 'The deployment target tag, e.g. prod-latest or dev-latest'
      target_env:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.target_env }}
    steps:
      - name: Set up SSH key for Production
        if: ${{ inputs.target_tag == 'prod-latest' }}
        # Sets up the SSH key for the production server if the target tag indicates production.
        run: |
          # Create the .ssh directory if it doesn't exist.
          mkdir -p ~/.ssh
          # Write the production SSH private key to file.
          echo "${{ secrets.PROD_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Add the production server to known_hosts to avoid authenticity prompts.
          ssh-keyscan -H ${{ secrets.PROD_SERVER }} >> ~/.ssh/known_hosts

      - name: Deploy to Production VPS
        if: ${{ inputs.target_tag == 'prod-latest' }}
        # Deploys to Production VPS if the target tag indicates production.
        run: |
          OWNER="${{ github.repository_owner }}"
          REPO="${{ github.event.repository.name }}"
          IMAGE="ghcr.io/$OWNER/$REPO:${{ inputs.target_tag }}"
          echo "Deploying $IMAGE to Production VPS..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.PROD_SSH_USER }}@${{ secrets.PROD_SERVER }} "\
            export PROJECT_NAME='rcb-discord-bot'
            export DEPLOY_ENV='prod' && \
            export GHCR_USER='${{ secrets.MACHINE_USER }}' && \
            export GHCR_PAT='${{ secrets.MACHINE_PAT }}' && \
            export APPLICATION_IMAGE='$IMAGE' && \
            /opt/rcb-deployments/discord-bot/deploy.sh $IMAGE"

      - name: Set up SSH key for Development
        if: ${{ inputs.target_tag == 'dev-latest' }}
        # Sets up the SSH key for the development server if the target tag indicates development.
        run: |
          # Create the .ssh directory if it doesn't exist.
          mkdir -p ~/.ssh
          # Write the development SSH private key to file.
          echo "${{ secrets.DEV_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Add the development server to known_hosts to avoid authenticity prompts.
          ssh-keyscan -H ${{ secrets.DEV_SERVER }} >> ~/.ssh/known_hosts

      - name: Deploy to Development VPS
        if: ${{ inputs.target_tag == 'dev-latest' }}
        # Deploys to Development VPS if the target tag indicates development.
        run: |
          OWNER="${{ github.repository_owner }}"
          REPO="${{ github.event.repository.name }}"
          IMAGE="ghcr.io/$OWNER/$REPO:${{ inputs.target_tag }}"
          echo "Deploying $IMAGE to Development VPS..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEV_SSH_USER }}@${{ secrets.DEV_SERVER }} "\
            export PROJECT_NAME='rcb-discord-bot'
            export DEPLOY_ENV='dev' && \
            export GHCR_USER='${{ secrets.MACHINE_USER }}' && \
            export GHCR_PAT='${{ secrets.MACHINE_PAT }}' && \
            export APPLICATION_IMAGE='$IMAGE' && \
            /opt/rcb-deployments/discord-bot/deploy.sh $IMAGE"
